---
- hosts: all
  become: yes

  vars:
    placeholder: "placecats.com"
    width: 400
    height: 600
    prefix: "ARTs Demo HashiCat"

  tasks:
    - name: Wait for SSH connection to become available
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 180
        sleep: 15
      register: connection_wait
      ignore_errors: yes

    - name: Check connection status
      debug:
        msg: "Host is reachable"
      when: connection_wait is succeeded

    - name: Gather facts manually
      ansible.builtin.setup:
      when: connection_wait is succeeded
      
    - name: Install httpd
      dnf:
        name: httpd
        state: latest

    - name: copying index.html to right place
      template:
        dest: /var/www/html/index.html
        src: index.html.j2
        mode: 0755

    - name: httpd service enabled
      service:
        name: httpd
        enabled: true
        state: started

    - name: install firewalld
      dnf:
        name: firewalld
        state: latest

    - name: firewalld service is started
      service:
        name: firewalld
        enabled: true
        state: started

    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
