---
- hosts: all
  become: yes

  vars:
    placeholder: "picsum.photos"
    width: 400
    height: 600
    prefix: "Terraform/Ansible Demo Picsum Photos"

  tasks:
    - name: Wait for SSH connection to become available
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 180
        sleep: 15
      register: connection_wait
      ignore_errors: yes

    - name: Check connection status
      debug:
        msg: "Host is reachable"
      when: connection_wait is succeeded

    - name: Gather facts manually
      ansible.builtin.setup:
      when: connection_wait is succeeded
      
    - name: Install httpd
      dnf:
        name: httpd
        state: latest

    - name: copying index.html to right place
      template:
        dest: /var/www/html/index.html
        src: index.html.j2
        mode: 0755

    - name: httpd service enabled
      service:
        name: httpd
        enabled: true
        state: started

    - name: install firewalld
      dnf:
        name: firewalld
        state: latest

    - name: firewalld service is started
      service:
        name: firewalld
        enabled: true
        state: started

    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
        
    - name: Check httpd service status
      command: systemctl is-active httpd
      register: httpd_status
      ignore_errors: yes
      when: connection_wait is succeeded

    - name: Get AWS public IP from metadata service
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        return_content: yes
        timeout: 5
      register: aws_public_ip
      ignore_errors: yes
      when: connection_wait is succeeded

    - name: Get Azure public IP from metadata service
      uri:
        url: http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress?api-version=2021-02-01&format=text
        return_content: yes
        timeout: 5
        headers:
          Metadata: "true"
      register: azure_public_ip
      ignore_errors: yes
      when: 
        - connection_wait is succeeded
        - aws_public_ip is failed

    - name: Debug Azure response
      debug:
        msg: "Azure response: '{{ azure_public_ip.content }}' (length: {{ azure_public_ip.content | length }})"
      when: 
        - connection_wait is succeeded
        - azure_public_ip is succeeded

    - name: Display webpage availability message (AWS)
      debug:
        msg: "The webpage is available at http://{{ aws_public_ip.content | trim }}"
      when: 
        - connection_wait is succeeded
        - aws_public_ip is succeeded
        - (aws_public_ip.content | trim) != ""

    - name: Display webpage availability message (Azure)
      debug:
        msg: "The webpage is available at http://{{ azure_public_ip.content | trim }}"
      when: 
        - connection_wait is succeeded
        - azure_public_ip is succeeded
        - (azure_public_ip.content | trim) != ""

    - name: Display webpage availability message (fallback)
      debug:
        msg: "The webpage is available at http://{{ ansible_default_ipv4.address }}"
      when: 
        - connection_wait is succeeded
        - (aws_public_ip is failed or (aws_public_ip.content | trim) == "")
        - (azure_public_ip is failed or (azure_public_ip.content | trim) == "")
